---

templates:
  - infrastructure/**/*.yaml

# File patterns to ignore
ignore_templates:
  - .cfnlintrc.yaml
  - .checkov.yaml
  - .github/**/*.yaml
  - .pre-commit-config.yaml
  - .pre-all.yaml
  - .woke.yaml
  - .yamllint.yml
  - infrastructure/**/build-spec.yaml
  - infrastructure/**/gitsync.yaml
  - lambdalayer/README.md
  - lambdalayer/runtime_config.json

ignore_bad_template: true
