AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Step 0: Deploy step-0 template in eu-west-2 which contains Secrets Manager config.

Parameters:
  Environment:
    Type: String
    Description: Deployment environment.
    Default: "development"
  SecretName:
    Description: Secret name
    Type: String
    Default: DynatraceSecrets
  RepositoryName:
    Type: String
    Default: "observability-infrastructure"
    Description: Name of the repository to connect to in GitHub
  KeySpec:
    Description: 'Specify the type of the CMK.'
    Type: String
    AllowedValues:
    - SYMMETRIC_DEFAULT
    - RSA_2048
    - RSA_3072
    - RSA_4096
    - ECC_NIST_P256
    - ECC_NIST_P384
    - ECC_NIST_P521
    - ECC_SECG_P256K1
    Default: SYMMETRIC_DEFAULT
  KeyUsage:
    Description: 'Which cryptographic operations should the CMK support?'
    Type: String
    AllowedValues:
    - ENCRYPT_DECRYPT
    - SIGN_VERIFY
    Default: ENCRYPT_DECRYPT
  DeletionPolicy:
    Description: 'Attribute you can preserve, and in some cases, backup a resource when its stack is deleted'
    Type: String
    AllowedValues:
    - Retain
    - Delete
    Default: Retain
  UpdateReplacePolicy:
    Description: 'Attribute to retain or, in some cases, backup the existing physical instance of a resource when it is replaced during a stack update operation.'
    Type: String
    AllowedValues:
    - Retain
    - Delete
    Default: Retain

Resources:
  DynatraceSecrets:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Properties:
      Description: Secret for Dynatrace integration
      Name: !Sub ${Environment}/${SecretName}
      KmsKeyId: !Ref KMSKey
      Tags:
        - Key: Service
          Value: aws-metric-streams-client
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: RepositoryName
          Value: !Sub ${RepositoryName}

  KMSKey:
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Type: 'AWS::KMS::Key'
    Properties:
      EnableKeyRotation: true
      KeySpec: !Ref KeySpec
      KeyUsage: !Ref KeyUsage
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: 'kms:*'
          Resource: '*'
        - Sid: AllowSecretsManagerAccess
          Effect: Allow
          Principal:
            Service:
              - secretsmanager.amazonaws.com
          Action:
            - "kms:Decrypt"
            - "kms:GenerateDataKey"
          Resource: "*"
      Tags:
        - Key: Service
          Value: aws-metric-streams-client
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: RepositoryName
          Value: !Sub ${RepositoryName}