AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastracture for CloudWatch Metric Streams and delivering to Dynatrace

Parameters:
  FirehoseHttpDeliveryEndpoint:
    Description: URL to which Firehose will deliver stream
    Type: String
    AllowedValues: ['https://aws.cloud.dynatrace.com','https://aws.cloud.dynatrace.com/','https://aws.cloud.dynatrace.com/metrics','https://us.aws.cloud.dynatrace.com','https://us.aws.cloud.dynatrace.com/','https://us.aws.cloud.dynatrace.com/metrics','https://eu.aws.cloud.dynatrace.com','https://eu.aws.cloud.dynatrace.com/','https://eu.aws.cloud.dynatrace.com/metrics']
    Default: 'https://aws.cloud.dynatrace.com/metrics'
  RequireValidCertificate:
    Description: Require valid SSL certificate for Dynatrace cluster communication
    Type: String
    AllowedValues: [true, false]
    Default: true
  SecretName:
    Description: Secret name
    Type: String  
    Default: DynatraceSecrets
  Environment:
    Description: Deployment environment
    Type: String
    Default: non-production
  RepositoryName:
    Description: Repository name
    Type: String
    Default: observability-infrastructure
  KeySpec:
    Description: 'Specify the type of the CMK.'
    Type: String
    AllowedValues:
    - SYMMETRIC_DEFAULT
    - RSA_2048
    - RSA_3072
    - RSA_4096
    - ECC_NIST_P256
    - ECC_NIST_P384
    - ECC_NIST_P521
    - ECC_SECG_P256K1
    Default: SYMMETRIC_DEFAULT
  KeyUsage:
    Description: 'Which cryptographic operations should the CMK support?'
    Type: String
    AllowedValues:
    - ENCRYPT_DECRYPT
    - SIGN_VERIFY
    Default: ENCRYPT_DECRYPT
  DeletionPolicy:
    Description: 'Attribute you can preserve, and in some cases, backup a resource when its stack is deleted' 
    Type: String
    AllowedValues:
    - Retain
    - Delete
    Default: Retain
  UpdateReplacePolicy:
    Description: 'Attribute to retain or, in some cases, backup the existing physical instance of a resource when it is replaced during a stack update operation.' 
    Type: String
    AllowedValues:
    - Retain
    - Delete
    Default: Retain

Resources:
  DynatraceSecrets:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Properties:
      Description: Secret for Dynatrace integration
      Name: !Sub ${Environment}/${SecretName}
      KmsKeyId: !Ref KMSKey
      Tags: 
        - Key: Service
          Value: aws-metric-streams-client
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: RepositoryName
          Value: !Sub ${RepositoryName}

  KMSKey:
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Type: 'AWS::KMS::Key'
    Properties:
      EnableKeyRotation: true
      KeySpec: !Ref KeySpec
      KeyUsage: !Ref KeyUsage
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: 'kms:*'
          Resource: '*'
        - Sid: AllowSecretsManagerAccess
          Effect: Allow
          Principal:
            Service: secretsmanager.amazonaws.com
          Action:
            - "kms:Decrypt"
            - "kms:GenerateDataKey"
          Resource: "*"
      Tags: 
        - Key: Service
          Value: aws-metric-streams-client
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: RepositoryName
          Value: !Sub ${RepositoryName}
          
  FirehoseMetricStreams:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      HttpEndpointDestinationConfiguration:
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 3
        EndpointConfiguration:
          AccessKey: !Sub "{{resolve:secretsmanager:${SecretName}:SecretString:DYNATRACE_API_KEY}}" # will update to ${Environment}/${SecretName} name after cutover
          Name: Dynatrace delivery endpoint
          Url: !Ref FirehoseHttpDeliveryEndpoint
        RequestConfiguration:
          CommonAttributes:
            - AttributeName: dt-url
              AttributeValue: !Sub "{{resolve:secretsmanager:${SecretName}:SecretString:DYNATRACE_ENVIRONMENT_URL}}" # will update to ${Environment}/${SecretName} name after cutover
            - AttributeName: require-valid-certificate
              AttributeValue: !Ref RequireValidCertificate
          ContentEncoding: GZIP
        RetryOptions:
          DurationInSeconds: 900
        S3BackupMode: FailedDataOnly
        S3Configuration:
          BucketARN: !GetAtt FailedDataBucket.Arn
          RoleARN: !GetAtt FailedDataBucketRole.Arn

  FailedDataBucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref FailedDataBucketRole
      PolicyName: firehose_delivery_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource:
              - !GetAtt FailedDataBucket.Arn
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref FailedDataBucket
                  - '*'

  FailedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
      VersioningConfiguration:
           Status: Enabled

  FailedDataBucketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'AWS::AccountId'

  MetricStreamsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - streams.metrics.cloudwatch.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'firehose:PutRecord'
                  - 'firehose:PutRecordBatch'
                Resource: !GetAtt FirehoseMetricStreams.Arn
      Description: A metric stream role

  MetricStream:
    Type: AWS::CloudWatch::MetricStream
    Properties:
      FirehoseArn: !GetAtt FirehoseMetricStreams.Arn
      IncludeLinkedAccountsMetrics: true
      RoleArn: !GetAtt MetricStreamsRole.Arn
      OutputFormat: 'opentelemetry0.7'
      StatisticsConfigurations:
        - AdditionalStatistics:
            - p95
            - p99
          IncludeMetrics:
            - MetricName: Latency
              Namespace: AWS/ApiGateway
