AWSTemplateFormatVersion: 2010-09-09
Description: Role able to be used by GitHub Actions

Resources:
  GitHubActionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DynatraceGitHubActionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                "token.actions.githubusercontent.com:sub":
                  - "repo:govuk-one-login/observability-infrastructure:*"
                  - "repo:govuk-one-login/observability-dynatrace-resources:*"
                  - "repo:govuk-one-login/observability-secrets:*"                  
                "token.actions.githubusercontent.com:aud": 
                  - "sts.amazonaws.com"
      Path: /
      Policies:
        - PolicyName: AssumeRole-DynatraceGitHubActionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:ListSecrets
                  - secretsmanager:CreateSecret                  
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - signer:StartSigningJob
                Resource: 'arn:aws:signer:eu-west-2:*:/signing-profiles/DynatraceSigner'
              - Effect: Allow
                Action:
                  - signer:DescribeSigningJob
                Resource: '*'
              - Effect: Allow
                Action:
                  - lambda:GetLayerVersion
                  - lambda:PublishLayerVersion
                  - lambda:AddLayerVersionPermission
                Resource: '*'
              - Effect: Allow
                Action:
                  - kms:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: 'arn:aws:dynamodb:*:*:table/terraform-state-lock-table'
              - Effect: Allow
                Action:
                  - iam:*
                Resource: '*'