name: Check PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

#Prevent default write-all access - this was pointed out by this checkov check CKV2_GHA_1
permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  run-cfn-lint:
    name: Run cfn-lint
    runs-on: ubuntu-22.04
    steps:
      - name: Run cfn-lint
        uses: govuk-one-login/github-actions/code-quality/check-linting@v1
        with:
          run-cfn-lint: false # until README.md is fixed
          run-prettier: false
          run-eslint: false

  run-checkov:
    name: Run Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
      - uses: govuk-one-login/org-github-actions/checkov@v1
        name: Run Checkov

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
      - uses: govuk-one-login/org-github-actions/pre-commit@v1
        with:
          python-version: 3.13                             # Optional, defaults to '3.13'

  pre-commit-all:
    runs-on: ubuntu-slim
    steps:
      - uses: ./.github/workflows/temptest
        with:
          python-version: 3.13                             # Optional, defaults to '3.13'
          all-files: true
          show-diff: true
          fail-fast: false

(Line: 19, Col: 15): Expected format {org}/{repo}[/path]@ref. Actual 'govuk-one-login/github-actions/code-quality/check-linting'
