name: Check PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

#Prevent default write-all access - this was pointed out by this checkov check CKV2_GHA_1
permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  run-cfn-lint:
    name: Run cfn-lint
    runs-on: ubuntu-22.04
    steps:
      - name: Run cfn-lin (from github-actions)
        uses: govuk-one-login/github-actions/code-quality/check-linting
        with:
          run-cfn-lint: false # until README.md is fixed
          run-prettier: false
          run-eslint: false

  run-checkov:
    name: Run Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Run Checko (from org-github-actions)
        uses: govuk-one-login/org-github-actions/checkov@v1

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Run pre-commit (from org-github-actions)
        uses: govuk-one-login/org-github-actions/pre-commit@v1
        with:
          python-version: 3.13                             # Optional, defaults to '3.13'
