name: reusable-action
description: "Test reusable action, with inputs"
run-name: Reusable

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
    type: string
#   pre-commit-tasks:
#     description: 'Comma separated list of tasks to run, or single task name'
#     required: true
  all-files:
    description: 'Boolean value to run pre-commit run --all-files ...'
    default: false
    required: false
    type: boolean
  show-diff:
    description: 'Boolean value to run pre-commit run --show-diff-on-failure ...'
    default: false
    required: false
    type: boolean
  fail-fast:
    description: 'Boolean value to run pre-commit run --fail-fast ...'
    default: false
    required: false
    type: boolean

runs:
    # runs-on: ubuntu-slim
    using: composite
    steps:
      # - uses: actions/checkout@v6
      # - name: "Reusable: Testing inputs"
      #   env:
      #     REUSABLE: true
      #     ALLFILES: ${{ inputs.all-files == 'true' }}
      #   shell: bash
      #   run: |
      #     echo "REUSABLE='${REUSABLE}'"
      #     echo "ALLFILES='${ALLFILES}'"
      #     echo "inputs.all-files: ${{ inputs.all-files }}"
      #     echo "inputs.show-diff: ${{ inputs.show-diff }}"
      #     echo "inputs.fail-fast: ${{ inputs.fail-fast }}"
      #     echo
      #
      - name: Check all-files
        if: ${{ inputs.all-files == 'true' }}
        shell: bash
        run: echo "PRE_COMMIT_ARGS=${PRE_COMMIT_ARGS} --all-files" >> $GITHUB_ENV

      - name: Check show-diff
        if: ${{ inputs.show-diff == 'true' }}
        shell: bash
        run: echo "PRE_COMMIT_ARGS=${PRE_COMMIT_ARGS} --show-diff-on-failure" >> $GITHUB_ENV

      - name: Check fail-fast
        if: ${{ inputs.fail-fast == 'true' }}
        shell: bash
        run: echo "PRE_COMMIT_ARGS=${PRE_COMMIT_ARGS} --fail-fast" >> $GITHUB_ENV

      # - name: Check pre-commit-args
      #   shell: bash
      #   run: |
      #     echo "PRE_COMMIT_ARGS='${PRE_COMMIT_ARGS}'"
      #     declare -p PRE_COMMIT_ARGS
      #     echo

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          # TODO? https://towardsdev.com/speed-up-you-github-actions-by-caching-you-python-packages-install-31127de213ae
          # cache: 'pip'
          # cache-dependency-path: ~/.cache/pre-commit
          # pip-install: pre-commit checkov yamllint codespell cfn-lint jschema-to-python sarif-om junit-xml pydot


      # - name: Cache pre-commit hooks
      #   # https://pragmaticnotes.hashnode.dev/running-pre-commit-in-a-reusable-github-actions-workflow-with-caching
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/pre-commit
      #     # key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      #     key: >
      #       ${{ format('pre-commit-{0}-{1}',
      #       steps.setup-python.outputs.python-version,
      #       hashFiles('.pre-commit-config.yaml')
      #       ) }}

      - name: Install pre-commit mfl using pip
        run: pip install pre-commit checkov yamllint codespell cfn-lint jschema-to-python sarif-om junit-xml pydot
        shell: bash

      - name: running pre-commit
        shell: bash
        run: |
          git config --global diff.wserrorhighlight all
          git config --global color.ui always
          echo
          echo "Running:"
          echo "go version"
          go version
          echo "Running:"
          echo "pre-commit run --color always --verbose ${PRE_COMMIT_ARGS} --config .pre-all.yaml | perl -e 's/ /.../'"
          echo
          pre-commit run --color always --verbose ${PRE_COMMIT_ARGS} --config .pre-all.yaml | perl -C -pe 's/^(\x{1b}\[\d+m)*(-.*?)([ \t]+)(\x{1b}\[m)*(\r?)$/$2 . ("\x{2423}" x (length($3) + 0)) . $4 . $5 . "\x24"/e'
          echo
